### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by vlee489** [BareConductive/bare-conductive-arduino#1]
I do python and my C is horrible. A bit of help please someone 

Touch_MP3.ino: In function 'void setup()':
Touch_MP3.ino:56:6: error: redefinition of 'void setup()'
sketch_sep19a.ino:1:6: error: 'void setup()' previously defined here
Touch_MP3.ino: In function 'void loop()':
Touch_MP3.ino:80:6: error: redefinition of 'void loop()'
sketch_sep19a.ino:6:6: error: 'void loop()' previously defined here

**Comment by stefandz** [comment]
Hi Vlee.

Sorry to hear that you are having problems. Have you followed the instructions [here](http://www.bareconductive.com/make/setting-up-arduino-with-your-touch-board/)? What operating system and Arduino version are you using?

S

**Comment by stefandz** [comment]
Hi again Vlee

Did you get anywhere with this? Should I mark this issue as closed?

S

**Comment by xhbang** [comment]
yes you can close it

It works fine on mac

—

**Comment by vlee489** [comment]
sorry not replying (was busy with school).
I got it working
