### ISSUE TITLE
macOS Catalina fix

### ISSUE THREAD

**Issue by JamesGreenaway** [BareConductive/bare-conductive-arduino#2]
Hey, I noticed that you have included a macOS Catalina fix in a recent commit, would it be possible for you to explain how to get this to work? I am struggling to get anything other than:

```
avrdude: ser_close(): can't reset attributes for device: Device not configured
the selected serial port avrdude: ser_close(): can't reset attributes for device: Device not configured
 does not exist or your board is not connected
```

**Comment by loosepascal** [comment]
Hi @JamesGreenaway, sorry I've only just seen this comment. You need to burn the bootloader on the Touch Board, we have explained the situation here: https://www.bareconductive.com/news/touch-board-and-macos-catalina/

You can find information on how to burn the bootloader here: https://arduino.stackexchange.com/questions/473/how-do-i-burn-the-bootloader

**Comment by sciciliani** [comment]
Hi @loosepascal, the bareconductive link is broken and I was looking for some info on how to burn the bootloader (pins, etc) to my bare conductive board as current macbook (Monterrey) is not detecting USB serial.
