### ISSUE TITLE
resolume arena gets crashed when enable midi input as long as the touch board is connected with computer

### ISSUE THREAD

**Issue by agalloch21** [BareConductive/bare-conductive-arduino#3]
we recently meet a problem when using touch board. we plan to use resolume arena to receive midi input, but resolume arena gets crashed when enable midi input as long as the touch board is connected with computer. 

- I tested other midi controller and they worked fine with resolume arena.

-  I tried to use touch board as keyboard and it worked fine. 

- I commented out all the code of the example "touch-usb-midi-interface" but the problem was still there. 

So I guess the problem may be inside the midi driver?

Arduino: 1.8.10
Resolume Arena: 6.1.10
BareConductive SDK: Latest on the website

**Comment by loosepascal** [comment]
This is not related to this repository, so I'm going to close this, but I've replied to your email!
